apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubanews-web-deployment
  labels:
    app: cubanews-web
    project: cubanews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cubanews-web
  template:
    metadata:
      labels:
        app: cubanews-web
    spec:
      containers:
        - name: cubanews-web
          image: us-east1-docker.pkg.dev/crawl-and-search/cubanews/cubanews-web:IMAGE_VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80