version: "3.9"
services:
  web:
    image: cubanews-web:local
    ports:
      - "80:80"
  
  api:
    image: cubanews-api:local
    ports:
      - "8080:8080"
    volumes:
      - vol1:/crawlers/

volumes:
  vol1: