version: "3.9"
services:
  web:
    image: ghcr.io/snava10/cubanews-web:main
    ports:
      - "80:80"
  
  api:
    image: ghcr.io/snava10/cubanews-rest-api:main
    ports:
      - "8080:8080"
    volumes:
      - vol1:/crawlers/
volumes:
  vol1: