apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
    project: cubanews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: cubanews-rest-api:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: storage
          mountPath: /tmp
      volumes:
      - name: storage
        emptyDir: {}
# TODO: Migrate to an external volume that will not be linked to the node.