apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubanews-web-deployment
  labels:
    app: cubanews-web
    project: cubanews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cubanews-web
  template:
    metadata:
      labels:
        app: cubanews-web
    spec:
      containers:
        - name: cubanews-web
          image: cubanews-web:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"